### PR TITLE
Add common nf-core/modules

### PR DESCRIPTION
**Pull request by abhi18av**
This PR adds the common `nf-core/modules` to the workflow.

There are many more tools which needs to be added, but as decided within the scope of https://github.com/nf-core/gwas/issues/16 , we'll be adding them as `local` modules first.

### CODE REVIEW

**Review by Mxrcon — APPROVED** [review]
I think that these modules are ready for testing and we can proceed with the merge, also the tests seems fine.  Just one thing: Are we going to add stubs for the processes?

**Comment by abhi18av** [comment]
@Mxrcon , stubs doesn't seem like a good way to go for the dev work since nf-core isn't relying on stubs so far. 

If we want to do workflow testing based on stubs, we'd have to customize the `modules/nf-core` modules, which defeats the idea of using `nf-core/modules`.

Thanks for the review Davi!

**Comment by abhi18av** [comment]
> I think that these modules are ready for testing ...

The nf-core modules are already tested based on small datasets in that repo, therefore we can use them directly.

**Comment by Mxrcon** [comment]
ohh True! i forgot that, nf-core modules are ready and tested, our local modules that will need testing.

**Pull request merged**
