### PR TITLE
initial dsl2 commit fresh template from `nf-core create`

### PR DESCRIPTION
**Pull request by alaincoletta**
## PR checklist

- [ x] This comment contains a description of changes (with reason)
- [ x] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ x] Documentation in `docs` is updated
- [ ] If necessary, also make a PR on the [nf-core/gwas branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/gwas)

### CODE REVIEW

**Comment by ewels** [comment]
Hi @alaincoletta,

Given that the [current commits](https://github.com/nf-core/gwas/commits/dev) on this repo are basically only vanilla template and updates, I think it might be tidied to just wipe all existing history and start fresh with an `nf-core create` command.

We can discuss this further on Slack, if you want to go this way it might be easiest if I set you up with the initial dsl2 template `nf-core create` command in this repo and do the wiping and then you start some PRs where you add the content.

How does this sound?

Phil

**Comment by abhi18av** [comment]
Hi @ewels, I think that should streamline things faster and for a while we could focus only on the PRs. What do you think @alaincoletta ?

**Comment by alaincoletta** [comment]
Yes, I agree. I believe the feature/dsl2 branch is from a fresh nf-core create command.

**Comment by ewels** [comment]
Ok, I have set up the repo with some new branches with a fresh start from the DSL2 template.

We will delete the existing branches soon, but until you are happy and have a new PR set up with the changes that you've written, we can leave them there so that no-one accidentally loses work. I have prefixed them with `OLD_` so that we know to delete them later.

Please pull these new changes from the main nf-core repo and branch off the new `dev` branch. You'll have to re-apply the edits that you've been working in this PR as they will now be on a fresh code base with no related git histories (this is why I was keen to do this ASAP before you got much further with your work).

Once you've transferred your new code, you can make a new PR against the new `dev` branch as normal.

**Comment by ewels** [comment]
ps. Generally speaking, we develop on forks and make PRs from there instead of using branches within the main nf-core repo. We're not super strict with this (eg. sometimes a branch is easier if there are lots of people working on the same feature), but it's what we recommend 👍🏻

**Pull request closed without merging**
